version: 0.2 
 
phases: 
 
  install: 
    commands: 
 
      # AWS Codebuild Go images use /go for the $GOPATH so let's symlink our 
      # application source code into that directory structure. 
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/handler" 
 
      # Install golint 
      - go get golang.org/x/lint/golint 
 
      # Install Testify to use common assertions and mocks in tests 
      - go get -u github.com/stretchr/testify 
 
  pre_build: 
    commands: 
 
      # Make sure we're in the project directory within our GOPATH 
      - cd "/go/src/handler" 
 
      # Fetch all dependencies 
      - go get ./... 
 
      # Ensure code passes all lint tests 
      - golint -set_exit_status 
 
      # Check for common Go application problems with 'go tool vet' 
      - go tool vet . 
 
      # Run all tests included with our application 
      - go test . 
 
  build: 
    commands: 
 
      # Build our go application 
      - go build -o main 
 
 artifacts: 
  type: zip